name: Deploy Container
on: [push]  # Triggers on every git push

jobs:
  deploy back:
    runs-on: ubuntu-latest 
    steps:
      - name: Sync repo
        run: |
          # set dir as safe
            docker exec gitea_runner \
              git config --global --add safe.directory /back
          # Fetch repo
            docker exec gitea_runner \
              git -C /back fetch "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/hackaton/back.git"
          # Sync repo
            docker exec gitea_runner \
              git -C /back reset --hard origin/main
              # git -C /back pull "https://phoenix381:${{ secrets.TOKEN }}@projects.root.sx/hackaton/back.git"
          # log
            docker exec gitea_runner \
              git -C /back status
      
      - name: Restart back
        run: |
          docker restart go_app